"""add user log

Revision ID: 28efbaf6e0bb
Revises: 3293555e5b24
Create Date: 2025-06-03 22:17:57.286169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28efbaf6e0bb'
down_revision = '3293555e5b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    # ### end Alembic commands ###
